CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username          VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255),
    verified          BOOLEAN                                 NOT NULL,
    verification_code VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_password UNIQUE (password);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);